export type FinanceInvoice = {
  id: string;
  sourceModule: string;
  counterpartyReferenceType?: string | null;
  counterpartyReferenceId?: string | null;
  counterpartyName?: string | null;
  businessContextType?: string | null;
  businessContextId?: string | null;
  businessContextLabel?: string | null;
  description?: string | null;
  status: string;
  currency: string;
  totalAmount: number;
  paidAmount: number;
  outstandingAmount: number;
  issuedAt?: string | null;
  dueAt?: string | null;
  paidAt?: string | null;
  canceledAt?: string | null;
  documentSeries?: string | null;
  documentNumber?: string | null;
  fiscalDocumentType?: string | null;
  fiscalStatus?: string | null;
  fiscalReference?: string | null;
  fiscalPayloadReference?: string | null;
  fiscalProviderCode?: string | null;
  issuerLegalName?: string | null;
  issuerDocumentType?: string | null;
  issuerDocumentNumber?: string | null;
  issuerStateRegistration?: string | null;
  issuerMunicipalRegistration?: string | null;
  issuerTaxRegimeCode?: string | null;
  recipientLegalName?: string | null;
  recipientDocumentType?: string | null;
  recipientDocumentNumber?: string | null;
  recipientStateRegistration?: string | null;
  recipientMunicipalRegistration?: string | null;
  recipientEmail?: string | null;
  createdAt: string;
  updatedAt: string;
};

export type FinanceCashMovement = {
  id: string;
  invoiceId?: string | null;
  paymentId?: string | null;
  direction: string;
  category: string;
  amount: number;
  currency: string;
  occurredAt: string;
  description?: string | null;
  createdAt: string;
  updatedAt: string;
};
